spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:15431/postgres
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  kafka:
    listener:
      ack-mode: manual
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
    cloud:
      zookeeper:
        config.enabled: false
        connect-string: localhost:2181
    replicas: 3
    partitions: 2

minio:
  url: http://localhost:9000
  port: 9000
  accessKey: user
  secretKey: password
  secure: false
  bucket: minio-storage
  image-size: 10485760
  ttlDays: 5

server:
  port: 8080

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855

imagga:
  authorization: YWNjXzVkYWUwNmJjMTM4NWQ1MzpjNTRhYzI1NDVhZTA4Mzg0MTI3Yjg1NDNkMmYzNTRhMw==

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 10
        slowCallDurationThreshold: 4s
        slowCallRateThreshold: 90
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        minimumNumberOfCalls: 10
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 100ms
        retryExceptions:
          - com.example.imageapi.exception.RetryableException
  ratelimiter:
    configs:
      default:
        limit-for-period: 3
        limit-refresh-period: 60s
        timeout-duration: 0s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  observations:
    annotations:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true