version: "3"
services:
  pg-auth-server-db:
    image: postgres:14-alpine3.18
    container_name: auth_server_db
    environment:
      POSTGRES_DB: "auth_server_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    volumes:
      - auth-server-db:/var/lib/postgresql/data
    ports:
      - "15432:5432"

volumes:
  auth-server-db:
